name: Release

env:
  REPO: dirstat

on:
  release:
    types: [ created ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: GOOS=linux GOARCH=amd64 go build .
      - name: Compress binaries
        run: |
          tar -czf $REPO$.tar.gz $REPO$
        shell: bash
      - name: Upload binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: $REPO$.tar.gz
          asset_name: ${{ env.REPO }}-${{ env.RELEASE_VERSION }}-linux-amd64.tar.gz
          tag: ${{ github.ref }}

  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: GOOS=windows GOARCH=amd64 go build .
      - name: Compress binaries
        run: |
          tar -czf $REPO$.tar.gz $REPO$.exe
        shell: bash
      - name: Upload binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: $REPO$.tar.gz
          asset_name: ${{ env.REPO }}-${{ env.RELEASE_VERSION }}-windows-amd64.tar.gz
          tag: ${{ github.ref }}

  build-macos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: GOOS=darwin GOARCH=amd64 go build .
      - name: Compress binaries
        run: |
          tar -czf $REPO$.tar.gz $REPO$
        shell: bash
      - name: Upload binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: $REPO$.tar.gz
          asset_name: ${{ env.REPO }}-${{ env.RELEASE_VERSION }}-macos-amd64.tar.gz
          tag: ${{ github.ref }}
